"""Update nullable constraints

Revision ID: 03a909965502
Revises: 44915cc77205
Create Date: 2023-11-25 23:40:01.041474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a909965502'
down_revision: Union[str, None] = '44915cc77205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'region',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('locations', 'province',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('locations', 'city_municipality',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('locations', 'barangay',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'locations', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    op.alter_column('locations', 'barangay',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('locations', 'city_municipality',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('locations', 'province',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('locations', 'region',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
