"""Drop redundant barangay column

Revision ID: 7951f53e1bb6
Revises: 03a909965502
Create Date: 2023-11-25 23:52:55.044664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7951f53e1bb6'
down_revision: Union[str, None] = '03a909965502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'barangay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('barangay', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
